// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz58a9EeeHjGWgEQRGoryvsXIoM-05Fek',
    appId: '1:847551509822:web:aac7fc882942bd9854e86f',
    messagingSenderId: '847551509822',
    projectId: 'eng-electron-433904-j5',
    authDomain: 'eng-electron-433904-j5.firebaseapp.com',
    storageBucket: 'eng-electron-433904-j5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSMNfqgBO-aN9Mo-Mj7H1C6yKPMcUYFOE',
    appId: '1:847551509822:android:3619348f3296eb7a54e86f',
    messagingSenderId: '847551509822',
    projectId: 'eng-electron-433904-j5',
    storageBucket: 'eng-electron-433904-j5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZeCS_A-T8RDXzVSZSdOIuv5snB13QOgA',
    appId: '1:847551509822:ios:5443f04266c2b38754e86f',
    messagingSenderId: '847551509822',
    projectId: 'eng-electron-433904-j5',
    storageBucket: 'eng-electron-433904-j5.firebasestorage.app',
    iosBundleId: 'com.example.autoFin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZeCS_A-T8RDXzVSZSdOIuv5snB13QOgA',
    appId: '1:847551509822:ios:5443f04266c2b38754e86f',
    messagingSenderId: '847551509822',
    projectId: 'eng-electron-433904-j5',
    storageBucket: 'eng-electron-433904-j5.firebasestorage.app',
    iosBundleId: 'com.example.autoFin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz58a9EeeHjGWgEQRGoryvsXIoM-05Fek',
    appId: '1:847551509822:web:5782f4d62194f00c54e86f',
    messagingSenderId: '847551509822',
    projectId: 'eng-electron-433904-j5',
    authDomain: 'eng-electron-433904-j5.firebaseapp.com',
    storageBucket: 'eng-electron-433904-j5.firebasestorage.app',
  );

}